name: Chamber of Secrets

on: [push]

jobs:
  howdy:
    runs-on: ubuntu-latest
    steps:
      - name: KnockKnock
        run: echo "There's somebody at the door!"

  validate_db:
    runs-on: ubuntu-latest
    steps:
      - name: MongoDB Install
        run: |
          echo "Installing MongoDB Tools"
          sudo apt-get update
          sudo apt-get install -y gnupg
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Validate DB
        env:
          MONGODB_URI: "mongodb+srv://khazaddum.vcmwm7d.mongodb.net/"
          MONGO_USER: "gimli"
        run: |
          echo "Pinging Khazad Dum"
          mongosh $MONGODB_URI --apiVersion 1 --username $MONGO_USER --eval "db.runCommand({ping: 1})" || echo "Khazad Dum is down"
